version: "3"

services:
  rest:
    build: ./fiistars-api
    image: fiistars-api
    container_name: fiistars-api
    environment:
      - APP_MYSQL_DNS_SERVER=*****
      - APP_MYSQL_PORT=3306
      - APP_MYSQL_DB=*****
      - APP_MYSQL_USERNAME=********
      - APP_MYSQL_PASSWORD=********
    ports:
      - "8081:8081"
    restart: always

    links:
      - redis

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"